# Generated by Django 3.2.9 on 2021-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.CharField(blank=True, choices=[('$ 112.5', '$ 112.5'), ('$ 62', '$ 62')], max_length=200, null=True),
        ),
    ]
