# Generated by Django 3.2.9 on 2021-11-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_alter_container_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
