# Generated by Django 3.2.9 on 2021-12-01 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_alter_boat_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='status',
        ),
        migrations.AddField(
            model_name='boat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 20, 0, 45, 505020)),
        ),
    ]
