# Generated by Django 3.2.9 on 2021-12-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_auto_20211201_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
