# Generated by Django 3.2.9 on 2021-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0012_auto_20211203_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContainerSide',
        ),
        migrations.DeleteModel(
            name='ContainerSize',
        ),
        migrations.DeleteModel(
            name='ContainerStatus',
        ),
        migrations.AlterField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.CharField(choices=[('$ 112.5', '$ 112.5'), ('$ 62', '$ 62')], default='$ 112.5', max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='size',
            field=models.CharField(choices=[('40ft', '40ft'), ('20ft', '20ft')], default='40ft', max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free')], default='Pending', max_length=200),
        ),
    ]
