# Generated by Django 3.2.9 on 2021-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0013_auto_20211203_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.CharField(choices=[('112.5', '112.5'), ('62', '62')], default='112.5', max_length=200),
        ),
    ]
