# Generated by Django 3.2.9 on 2021-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0015_alter_container_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
