# Generated by Django 3.2.9 on 2021-12-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0017_alter_container_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.CharField(choices=[('112.5', '112.5'), ('62', '62')], default='112.5', max_length=200),
        ),
    ]
